name: Deploy to Amazon ECS

on:
  push:
    branches: [ "main" ]
      path: back
permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.BACK_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.BACK_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Create_pem
      run: |
      echo ${{ secrets.BACK_PEM_FILE }} | base64 --decode > backkey.pem

    steps:
    - name: cd back
    run: cd back

    - name: install dependencies
    run: npm install

    - name: Uploads
    run: scp -i [] -r [] ubuntu@[]

    steps:
    - name: Join Server
    run: ssh -i []

    - name: Nginx Restart
    run: systemctl restart nginx

    - name: Exit Server
    run: exit