name: Deploy to Amazon ECS

on:
  push:
    branches: [ "main" ]
permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Use PEM file in GitHub Actions
      env:
        PEM_FILE: ${{ secrets.PEM_FILE}}
      run: echo "${PEM_FILE}" > mango.pem

    - name: SSH to remote server using PEM file
      run: ssh -i mango.pem ubuntu@ec2-3-35-146-98.ap-northeast-2.compute.amazonaws.com

    - name: Access
      run: exit

    # steps:
    # - name: cd front
    # run: cd front

    # - name: install dependencies
    # run: npm install

    # - name: Build
    # run: npm run build
    
    # - name: Uploads
    # run: scp -i [] -r [] ubuntu@[]

    # steps:
    # - name: Join Server
    # run: ssh -i []

    # - name: Nginx Restart
    # run: systemctl restart nginx

    # - name: Exit Server
    # run: exit