name: Build and upload React app to EC2 instance
on:
  # pull_request:
  push:
    branches:
      - main
jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y nodejs
        sudo apt-get install -y npm
    - name: Build React app
      run: |
        cd front
        npm install
        npm run build
    - name: Upload build floder to EC2 instance
      env:
        SSH_PEM_FILE: ${{ secrets.SSH_PEM_FILE }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
      run: |
        echo "${SSH_PEM_FILE}" > githubAction.pem
        chmod 600 githubAction.pem
        mkdir -p ~/.ssh
        ssh-keyscan -t rsa ${EC2_HOST} >> ~/.ssh/known_hosts
        scp -i /home/runner/work/actions_practice/actions_practice/githubAction.pem -r ./build ${EC2_USER}@${EC2_HOST}:/home/ubuntu/www
    # - name: Upload to EC2
    #   uses: appleboy/scp-action@master
    #   env:
    #     SSH_PEM_FILE: ${{ secrets.SSH_PEM_FILE }}
    #     EC2_HOST: ${{ secrets.EC2_HOST }}
    #     EC2_USER: ${{ secrets.EC2_USER }}

    #   with:
    #     local: 'build/'
    #     remote_path: '/home/ec2-user/react-build/'
    #     host: ${{ secrets.EC2_HOST }}
    #     username: ${{ secrets.EC2_USER }}
    #     key: ${{ secrets.SSH_PEM_FILE }}