name: Mango_Market Practice
run-name: first_workflows
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install dependencies
      run: npm install
      - name: Build
      run: npm run build
      - name: file uploads
      run: scp -i [keyvalue] -r [localpath] 계정@호스트:[디렉토리 경로]
